version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: gaimplan-neo4j-shared
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - gaimplan-neo4j-data:/data
      - gaimplan-neo4j-logs:/logs
      - gaimplan-neo4j-import:/import
      - gaimplan-neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: gaimplan-qdrant-shared
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - gaimplan-qdrant-storage:/qdrant/storage
      - gaimplan-qdrant-snapshots:/qdrant/snapshots
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  gaimplan-neo4j-data:
  gaimplan-neo4j-logs:
  gaimplan-neo4j-import:
  gaimplan-neo4j-plugins:
  gaimplan-qdrant-storage:
  gaimplan-qdrant-snapshots:

networks:
  default:
    name: gaimplan-knowledge-network
    driver: bridge